USE [Leoni_Tsk_JN]
GO

/****** Object:  Index [Name_Index]    Script Date: 08/16/2014 19:55:10 ******/
CREATE UNIQUE NONCLUSTERED INDEX [Name_Index] ON [dbo].[User] 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


