#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brilliantech.PackSysDataService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LeoniPacking_prod")]
	public partial class PackSysDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public PackSysDataClassesDataContext() : 
				base(global::Brilliantech.PackSysDataService.Properties.Settings.Default.LeoniPacking_prodConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PackSysDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackSysDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackSysDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackSysDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PackItemView> PackItemView
		{
			get
			{
				return this.GetTable<PackItemView>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PackItemView")]
	public partial class PackItemView
	{
		
		private string _packageID;
		
		private string _projectID;
		
		private string _wrkStnID;
		
		private string _partNr;
		
		private System.DateTime _packagingTime;
		
		public PackItemView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packageID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string packageID
		{
			get
			{
				return this._packageID;
			}
			set
			{
				if ((this._packageID != value))
				{
					this._packageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string projectID
		{
			get
			{
				return this._projectID;
			}
			set
			{
				if ((this._projectID != value))
				{
					this._projectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wrkStnID", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string wrkStnID
		{
			get
			{
				return this._wrkStnID;
			}
			set
			{
				if ((this._wrkStnID != value))
				{
					this._wrkStnID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partNr", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string partNr
		{
			get
			{
				return this._partNr;
			}
			set
			{
				if ((this._partNr != value))
				{
					this._partNr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packagingTime", DbType="DateTime NOT NULL")]
		public System.DateTime packagingTime
		{
			get
			{
				return this._packagingTime;
			}
			set
			{
				if ((this._packagingTime != value))
				{
					this._packagingTime = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
