USE [master]
GO

/****** Object:  Database [Leoni_Tsk_JN]    Script Date: 08/07/2014 19:01:28 ******/
CREATE DATABASE [Leoni_Tsk_JN] ON  PRIMARY 
( NAME = N'Leoni_Tsk_JN', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Leoni_Tsk_JN.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Leoni_Tsk_JN_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Leoni_Tsk_JN_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Leoni_Tsk_JN] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Leoni_Tsk_JN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Leoni_Tsk_JN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET ARITHABORT OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET  READ_WRITE 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET  MULTI_USER 
GO

ALTER DATABASE [Leoni_Tsk_JN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Leoni_Tsk_JN] SET DB_CHAINING OFF 
GO


