#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brilliantech.Tsk.Data.CL.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Leoni_Tsk_JN")]
	public partial class TskDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertInspectOrigin(InspectOrigin instance);
    partial void UpdateInspectOrigin(InspectOrigin instance);
    partial void DeleteInspectOrigin(InspectOrigin instance);
    partial void InsertInspect(Inspect instance);
    partial void UpdateInspect(Inspect instance);
    partial void DeleteInspect(Inspect instance);
    partial void InsertUserTsk(UserTsk instance);
    partial void UpdateUserTsk(UserTsk instance);
    partial void DeleteUserTsk(UserTsk instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public TskDataDataContext() : 
				base(global::Brilliantech.Tsk.Data.CL.Properties.Settings.Default.Leoni_Tsk_JNConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TskDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TskDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TskDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TskDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InspectOrigin> InspectOrigin
		{
			get
			{
				return this.GetTable<InspectOrigin>();
			}
		}
		
		public System.Data.Linq.Table<Inspect> Inspect
		{
			get
			{
				return this.GetTable<Inspect>();
			}
		}
		
		public System.Data.Linq.Table<UserInspect> UserInspect
		{
			get
			{
				return this.GetTable<UserInspect>();
			}
		}
		
		public System.Data.Linq.Table<UserTsk> UserTsk
		{
			get
			{
				return this.GetTable<UserTsk>();
			}
		}
		
		public System.Data.Linq.Table<User> User
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InspectOrigin")]
	public partial class InspectOrigin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Text;
		
		private System.Nullable<bool> _ProcessResult;
		
		private string _ProcessMessage;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnProcessResultChanging(System.Nullable<bool> value);
    partial void OnProcessResultChanged();
    partial void OnProcessMessageChanging(string value);
    partial void OnProcessMessageChanged();
    partial void OnCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedAtChanged();
    #endregion
		
		public InspectOrigin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessResult", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> ProcessResult
		{
			get
			{
				return this._ProcessResult;
			}
			set
			{
				if ((this._ProcessResult != value))
				{
					this.OnProcessResultChanging(value);
					this.SendPropertyChanging();
					this._ProcessResult = value;
					this.SendPropertyChanged("ProcessResult");
					this.OnProcessResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessMessage", DbType="VarChar(1000)", UpdateCheck=UpdateCheck.Never)]
		public string ProcessMessage
		{
			get
			{
				return this._ProcessMessage;
			}
			set
			{
				if ((this._ProcessMessage != value))
				{
					this.OnProcessMessageChanging(value);
					this.SendPropertyChanging();
					this._ProcessMessage = value;
					this.SendPropertyChanged("ProcessMessage");
					this.OnProcessMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inspect")]
	public partial class Inspect : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _TskNo;
		
		private string _LeoniNo;
		
		private string _CusNo;
		
		private string _ClipScanNo;
		
		private System.Nullable<System.DateTime> _ClipScanTime1;
		
		private System.Nullable<System.DateTime> _ClipScanTime2;
		
		private string _TskScanNo;
		
		private System.Nullable<System.DateTime> _TskScanTime3;
		
		private System.Nullable<double> _Time3MinTime2;
		
		private string _OkOrNot;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private System.Nullable<System.Guid> _OriginId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnTskNoChanging(string value);
    partial void OnTskNoChanged();
    partial void OnLeoniNoChanging(string value);
    partial void OnLeoniNoChanged();
    partial void OnCusNoChanging(string value);
    partial void OnCusNoChanged();
    partial void OnClipScanNoChanging(string value);
    partial void OnClipScanNoChanged();
    partial void OnClipScanTime1Changing(System.Nullable<System.DateTime> value);
    partial void OnClipScanTime1Changed();
    partial void OnClipScanTime2Changing(System.Nullable<System.DateTime> value);
    partial void OnClipScanTime2Changed();
    partial void OnTskScanNoChanging(string value);
    partial void OnTskScanNoChanged();
    partial void OnTskScanTime3Changing(System.Nullable<System.DateTime> value);
    partial void OnTskScanTime3Changed();
    partial void OnTime3MinTime2Changing(System.Nullable<double> value);
    partial void OnTime3MinTime2Changed();
    partial void OnOkOrNotChanging(string value);
    partial void OnOkOrNotChanged();
    partial void OnCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedAtChanged();
    partial void OnOriginIdChanging(System.Nullable<System.Guid> value);
    partial void OnOriginIdChanged();
    #endregion
		
		public Inspect()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskNo", DbType="VarChar(100)")]
		public string TskNo
		{
			get
			{
				return this._TskNo;
			}
			set
			{
				if ((this._TskNo != value))
				{
					this.OnTskNoChanging(value);
					this.SendPropertyChanging();
					this._TskNo = value;
					this.SendPropertyChanged("TskNo");
					this.OnTskNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeoniNo", DbType="VarChar(100)")]
		public string LeoniNo
		{
			get
			{
				return this._LeoniNo;
			}
			set
			{
				if ((this._LeoniNo != value))
				{
					this.OnLeoniNoChanging(value);
					this.SendPropertyChanging();
					this._LeoniNo = value;
					this.SendPropertyChanged("LeoniNo");
					this.OnLeoniNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CusNo", DbType="VarChar(100)")]
		public string CusNo
		{
			get
			{
				return this._CusNo;
			}
			set
			{
				if ((this._CusNo != value))
				{
					this.OnCusNoChanging(value);
					this.SendPropertyChanging();
					this._CusNo = value;
					this.SendPropertyChanged("CusNo");
					this.OnCusNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanNo", DbType="VarChar(100)")]
		public string ClipScanNo
		{
			get
			{
				return this._ClipScanNo;
			}
			set
			{
				if ((this._ClipScanNo != value))
				{
					this.OnClipScanNoChanging(value);
					this.SendPropertyChanging();
					this._ClipScanNo = value;
					this.SendPropertyChanged("ClipScanNo");
					this.OnClipScanNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanTime1", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClipScanTime1
		{
			get
			{
				return this._ClipScanTime1;
			}
			set
			{
				if ((this._ClipScanTime1 != value))
				{
					this.OnClipScanTime1Changing(value);
					this.SendPropertyChanging();
					this._ClipScanTime1 = value;
					this.SendPropertyChanged("ClipScanTime1");
					this.OnClipScanTime1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanTime2", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClipScanTime2
		{
			get
			{
				return this._ClipScanTime2;
			}
			set
			{
				if ((this._ClipScanTime2 != value))
				{
					this.OnClipScanTime2Changing(value);
					this.SendPropertyChanging();
					this._ClipScanTime2 = value;
					this.SendPropertyChanged("ClipScanTime2");
					this.OnClipScanTime2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskScanNo", DbType="VarChar(100)")]
		public string TskScanNo
		{
			get
			{
				return this._TskScanNo;
			}
			set
			{
				if ((this._TskScanNo != value))
				{
					this.OnTskScanNoChanging(value);
					this.SendPropertyChanging();
					this._TskScanNo = value;
					this.SendPropertyChanged("TskScanNo");
					this.OnTskScanNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskScanTime3", DbType="DateTime")]
		public System.Nullable<System.DateTime> TskScanTime3
		{
			get
			{
				return this._TskScanTime3;
			}
			set
			{
				if ((this._TskScanTime3 != value))
				{
					this.OnTskScanTime3Changing(value);
					this.SendPropertyChanging();
					this._TskScanTime3 = value;
					this.SendPropertyChanged("TskScanTime3");
					this.OnTskScanTime3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time3MinTime2", DbType="Float")]
		public System.Nullable<double> Time3MinTime2
		{
			get
			{
				return this._Time3MinTime2;
			}
			set
			{
				if ((this._Time3MinTime2 != value))
				{
					this.OnTime3MinTime2Changing(value);
					this.SendPropertyChanging();
					this._Time3MinTime2 = value;
					this.SendPropertyChanged("Time3MinTime2");
					this.OnTime3MinTime2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkOrNot", DbType="VarChar(50)")]
		public string OkOrNot
		{
			get
			{
				return this._OkOrNot;
			}
			set
			{
				if ((this._OkOrNot != value))
				{
					this.OnOkOrNotChanging(value);
					this.SendPropertyChanging();
					this._OkOrNot = value;
					this.SendPropertyChanged("OkOrNot");
					this.OnOkOrNotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> OriginId
		{
			get
			{
				return this._OriginId;
			}
			set
			{
				if ((this._OriginId != value))
				{
					this.OnOriginIdChanging(value);
					this.SendPropertyChanging();
					this._OriginId = value;
					this.SendPropertyChanged("OriginId");
					this.OnOriginIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInspect")]
	public partial class UserInspect
	{
		
		private System.Guid _Id;
		
		private string _TskNo;
		
		private string _LeoniNo;
		
		private string _CusNo;
		
		private string _ClipScanNo;
		
		private System.Nullable<System.DateTime> _ClipScanTime1;
		
		private System.Nullable<System.DateTime> _ClipScanTime2;
		
		private string _TskScanNo;
		
		private System.Nullable<System.DateTime> _TskScanTime3;
		
		private System.Nullable<double> _Time3MinTime2;
		
		private string _OkOrNot;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private System.Nullable<System.Guid> _OriginId;
		
		private System.Nullable<int> _UserId;
		
		public UserInspect()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskNo", DbType="VarChar(100)")]
		public string TskNo
		{
			get
			{
				return this._TskNo;
			}
			set
			{
				if ((this._TskNo != value))
				{
					this._TskNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeoniNo", DbType="VarChar(100)")]
		public string LeoniNo
		{
			get
			{
				return this._LeoniNo;
			}
			set
			{
				if ((this._LeoniNo != value))
				{
					this._LeoniNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CusNo", DbType="VarChar(100)")]
		public string CusNo
		{
			get
			{
				return this._CusNo;
			}
			set
			{
				if ((this._CusNo != value))
				{
					this._CusNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanNo", DbType="VarChar(100)")]
		public string ClipScanNo
		{
			get
			{
				return this._ClipScanNo;
			}
			set
			{
				if ((this._ClipScanNo != value))
				{
					this._ClipScanNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanTime1", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClipScanTime1
		{
			get
			{
				return this._ClipScanTime1;
			}
			set
			{
				if ((this._ClipScanTime1 != value))
				{
					this._ClipScanTime1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanTime2", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClipScanTime2
		{
			get
			{
				return this._ClipScanTime2;
			}
			set
			{
				if ((this._ClipScanTime2 != value))
				{
					this._ClipScanTime2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskScanNo", DbType="VarChar(100)")]
		public string TskScanNo
		{
			get
			{
				return this._TskScanNo;
			}
			set
			{
				if ((this._TskScanNo != value))
				{
					this._TskScanNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskScanTime3", DbType="DateTime")]
		public System.Nullable<System.DateTime> TskScanTime3
		{
			get
			{
				return this._TskScanTime3;
			}
			set
			{
				if ((this._TskScanTime3 != value))
				{
					this._TskScanTime3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time3MinTime2", DbType="Float")]
		public System.Nullable<double> Time3MinTime2
		{
			get
			{
				return this._Time3MinTime2;
			}
			set
			{
				if ((this._Time3MinTime2 != value))
				{
					this._Time3MinTime2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkOrNot", DbType="VarChar(50)")]
		public string OkOrNot
		{
			get
			{
				return this._OkOrNot;
			}
			set
			{
				if ((this._OkOrNot != value))
				{
					this._OkOrNot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this._CreatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> OriginId
		{
			get
			{
				return this._OriginId;
			}
			set
			{
				if ((this._OriginId != value))
				{
					this._OriginId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTsk")]
	public partial class UserTsk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _UserId;
		
		private string _TskNo;
		
		private EntityRef<User> _User;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnTskNoChanging(string value);
    partial void OnTskNoChanged();
    #endregion
		
		public UserTsk()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskNo", DbType="VarChar(50)")]
		public string TskNo
		{
			get
			{
				return this._TskNo;
			}
			set
			{
				if ((this._TskNo != value))
				{
					this.OnTskNoChanging(value);
					this.SendPropertyChanging();
					this._TskNo = value;
					this.SendPropertyChanged("TskNo");
					this.OnTskNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserTsk", Storage="_User", ThisKey="UserId", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.UserTsk.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.UserTsk.Add(this);
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Password;
		
		private string _Role;
		
		private string _Email;
		
		private string _Department;
		
		private string _Phone;
		
		private System.Nullable<System.DateTime> _LastLoginTime;
		
		private EntitySet<UserTsk> _UserTsk;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnLastLoginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginTimeChanged();
    #endregion
		
		public User()
		{
			this._UserTsk = new EntitySet<UserTsk>(new Action<UserTsk>(this.attach_UserTsk), new Action<UserTsk>(this.detach_UserTsk));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(50)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(50)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginTime
		{
			get
			{
				return this._LastLoginTime;
			}
			set
			{
				if ((this._LastLoginTime != value))
				{
					this.OnLastLoginTimeChanging(value);
					this.SendPropertyChanging();
					this._LastLoginTime = value;
					this.SendPropertyChanged("LastLoginTime");
					this.OnLastLoginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_UserTsk", Storage="_UserTsk", ThisKey="Id", OtherKey="UserId")]
		public EntitySet<UserTsk> UserTsk
		{
			get
			{
				return this._UserTsk;
			}
			set
			{
				this._UserTsk.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserTsk(UserTsk entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_UserTsk(UserTsk entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
}
#pragma warning restore 1591
