#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brilliantech.Tsk.Data.CL.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Leoni_Tsk_JN")]
	public partial class TskDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public TskDataDataContext() : 
				base(global::Brilliantech.Tsk.Data.CL.Properties.Settings.Default.Leoni_Tsk_JNConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TskDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TskDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TskDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TskDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Inspect> Inspect
		{
			get
			{
				return this.GetTable<Inspect>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inspect")]
	public partial class Inspect
	{
		
		private string _TskNo;
		
		private string _LeoniNo;
		
		private string _CusNo;
		
		private string _ClipScanNo;
		
		private System.Nullable<System.DateTime> _ClipScanTime1;
		
		private System.Nullable<System.DateTime> _ClipScanTime2;
		
		private string _TskScanNo;
		
		private System.Nullable<System.DateTime> _TskScanTime3;
		
		private string _OkOrNot;
		
		public Inspect()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskNo", DbType="VarChar(50)")]
		public string TskNo
		{
			get
			{
				return this._TskNo;
			}
			set
			{
				if ((this._TskNo != value))
				{
					this._TskNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeoniNo", DbType="VarChar(50)")]
		public string LeoniNo
		{
			get
			{
				return this._LeoniNo;
			}
			set
			{
				if ((this._LeoniNo != value))
				{
					this._LeoniNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CusNo", DbType="VarChar(50)")]
		public string CusNo
		{
			get
			{
				return this._CusNo;
			}
			set
			{
				if ((this._CusNo != value))
				{
					this._CusNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanNo", DbType="VarChar(100)")]
		public string ClipScanNo
		{
			get
			{
				return this._ClipScanNo;
			}
			set
			{
				if ((this._ClipScanNo != value))
				{
					this._ClipScanNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanTime1", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClipScanTime1
		{
			get
			{
				return this._ClipScanTime1;
			}
			set
			{
				if ((this._ClipScanTime1 != value))
				{
					this._ClipScanTime1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClipScanTime2", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClipScanTime2
		{
			get
			{
				return this._ClipScanTime2;
			}
			set
			{
				if ((this._ClipScanTime2 != value))
				{
					this._ClipScanTime2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskScanNo", DbType="VarChar(100)")]
		public string TskScanNo
		{
			get
			{
				return this._TskScanNo;
			}
			set
			{
				if ((this._TskScanNo != value))
				{
					this._TskScanNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TskScanTime3", DbType="DateTime")]
		public System.Nullable<System.DateTime> TskScanTime3
		{
			get
			{
				return this._TskScanTime3;
			}
			set
			{
				if ((this._TskScanTime3 != value))
				{
					this._TskScanTime3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkOrNot", DbType="NChar(10)")]
		public string OkOrNot
		{
			get
			{
				return this._OkOrNot;
			}
			set
			{
				if ((this._OkOrNot != value))
				{
					this._OkOrNot = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
