//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brilliantech.Tsk.ConsoleCmd.InspectService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InspectService.IInspectService")]
    public interface IInspectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInspectService/CreateInspect", ReplyAction="http://tempuri.org/IInspectService/CreateInspectResponse")]
        Brilliantech.Framwork.Message.ProcessMessage CreateInspect(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInspectServiceChannel : Brilliantech.Tsk.ConsoleCmd.InspectService.IInspectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InspectServiceClient : System.ServiceModel.ClientBase<Brilliantech.Tsk.ConsoleCmd.InspectService.IInspectService>, Brilliantech.Tsk.ConsoleCmd.InspectService.IInspectService {
        
        public InspectServiceClient() {
        }
        
        public InspectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InspectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InspectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InspectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Brilliantech.Framwork.Message.ProcessMessage CreateInspect(string text) {
            return base.Channel.CreateInspect(text);
        }
    }
}
